# Permalinks
permalink:           pretty

# Setup
title:               'blog.genos.se'
url:                 https://blog.genos.se
tagline:             'thoughts from pelgo14'
baseurl:             ""

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              pelgo14
  url:               https://blog.genos.se
  email:             pelgo14@pm.me

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/pelgo14/pelgo14.github.io

plugins:
  - jemoji
