# Permalinks
permalink:           pretty

# Setup
title:               'p14'
url:                 https://pelgo14.github.io
tagline:             'thoughts from pelgo14'
baseurl:             ""

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              pelgo14
  url:               https://pelgo14.github.io
  email:             pelgo14@protonmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/pelgo14/pelgo14.github.io
