# Permalinks
permalink:           pretty

# Setup
title:               'blog.genos.se'
url:                 https://blog.genos.se
tagline:             'thoughts from giftmischer69'
baseurl:             ""

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              giftmischer69
  url:               https://blog.genos.se
  email:             giftmischer69@pm.me

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/giftmischer69/giftmischer69.github.io

plugins:
  - jemoji
